### ISSUE TITLE
Release of development vagrantfile for version 1.0.0

### ISSUE THREAD

**Issue by kk86bioinfo** [sentora/sentora-vagrant#1]
May I know when will be a push of vagrant file for Sentora to this repo?

**Comment by allebb** [comment]
The task of getting this set-up has been assigned to @trojanspike - He should be able to give you an update!

Although I see he recently (yesterday evening) added on here:- https://github.com/sentora/sentora-installers

So maybe he has decided to push the Vagrant file(s) into the `sentora-installers` repo instead? - He should be able to provide an answer shortly though :)

**Comment by trojanspike** [comment]
:+1:
