### ISSUE TITLE
How I can fix this error?

### ISSUE THREAD

**Issue by paulvilla** [sentora/sentora-vagrant#2]
I do not know how I can fix this error:

vm:
- The host path of the shared folder is missing: ~/themes/sentora/glass

EDIT:
I removed to DevConfig.yaml the following lines, so if I work:
- path: ~/themes/sentora/glass
  name: glass

Can this create an error in VM?

**Comment by trojanspike** [comment]
It's not an error

Change : https://github.com/sentora/sentora-vagrant/blob/develop/DevConfig.yaml#L30
to the correct path or remove , the array mounts the folders.

Bare in mind that there is no installer | provisioner yet. Something you can work on if you're up for it
https://github.com/sentora/sentora-vagrant/tree/develop/Setup/provisions
